### ISSUE TITLE
Show zoom in result directly above the mouse

### ISSUE THREAD

**Issue by 9mido** [stuartlangridge/magnus#19]
In addition to viewing the zoomed in area in a separate window, have the option to zoom like the following image where it directly shows a zoom in effect where the mouse is currently pointing:

![dQmB9jw](https://user-images.githubusercontent.com/60831272/140633739-83552adc-9ddc-45b0-8567-c3638b538094.png)

**Comment by stuartlangridge** [comment]
This isn't really magnus's goal, for a couple of reasons. The first is that one of the subsidiary use-cases for magnus is people studying something at zoom as well as studying it at normal resolution: graphic designers and the like, being able to see both at once. This isn't the primary intention for magnus, which is around accessibility, but it's an important secondary use. The second is technical: zooming at the mouse location requires overriding what the mouse pointer looks like to be a zoomed version of the screen. This is fraught with difficulty, and can be terribly flickery and unpleasant in certain situations, for reasons caused by the graphics driver or hardware and which are not sensibly fixable or even detectable by magnus. The reason I know this is that magnus grew out of Pick (https://kryogenix.org/code/pick) and doing this mouse cursor trick is exactly what Pick does, and there have been a persistent stream of bug reports about cursor flickering. This is not good in general and even less good as part of an accessibility tool. So, although I think this is a good idea in theory, I think that the code to do it should be another programme; magnus won't be doing this, although if someone wanted to take the magnus (and Pick) code and make something that did do it, I would think that was a good idea.

**Comment by 9mido** [comment]
@stuartlangridge I respect your decision and reasoning and was able to find an alternative. For anyone else looking for what I was describing:

http://magnifier.sourceforge.net
sudo apt install libgtk2.0-0:i386
./magnifier
