### ISSUE TITLE
Integrating into budgie-desktop

### ISSUE THREAD

**Issue by fossfreedom** [stuartlangridge/magnus#4]
Hi,

  excellent project!  We are definitely very interested with including your project into Ubuntu Budgie & I guess potentially all distros running budgie-desktop.

Have you any thoughts how magnus could be extended to respond to enable it to listen for  (for example) a dbus call to close the app.  I'm trying to think of a non-hacky way to open/close magnus via a keyboard shortcut.  In budgie that is currently the same as in GNOME Shell Alt+Super+8 to toggle zoom.

Secondly, any thoughts on how magnus (once it is running) could respond to a keyboard shortcut to zoom in/zoom out i.e. to increase/decrease the magnification?

**Comment by stuartlangridge** [comment]
These are good questions. The actual technical implementations probably aren't hard, but it's really a question of how it integrates with the desktop. Launching an app with a keyboard shortcut is a thing configured within the desktop itself; I don't know how Budgie does it, but Ubuntu MATE has a "keyboard shortcuts" control panel which has a "Toggle Magnifier" entry within it. I don't know what that actually _does_. Having Magnus respond to a D-Bus name, or giving it a `--toggle` command line option which starts it if not running and stops it otherwise is not hard; what I don't know is what I _should_ do here. @flexiondotorg can perhaps comment for Ubuntu MATE since I know they're working on this too; I'm sure there must be some sort of standard way to launch "the desktop magnifier" whatever that is, which each desktop implements, and then Magnus can just do whatever it needs to to _be_ that "desktop magnifier". (If there isn't such a standard then inventing one seems sensible.) Does Budgie already have a "launch desktop magnifier" option in its global keyboard shortcuts control panel? If it does... what does using that keypress actually do?

Responding to a keyboard shortcut to zoom would probably best be done with Keybinder (https://lazka.github.io/pgi-docs/Keybinder-3.0/index.html). However, claiming a global shortcut is always tricky, because it may conflict with other apps. (And Magnus is deliberately small and unconfigurable; I don't want to add a settings window to it to allow configuration of such a key.) So... what would the proposed keybinding be? `Ctrl Super +` and `Ctrl Super -` seem obvious choices, by analogy with the already-existing `Ctrl +` and `Ctrl -` used by web browsers to zoom.

**Comment by stuartlangridge** [comment]
I've added a draft cut of using `Ctrl Super +` and `Ctrl Super -` as keyboard shortcuts for zooming, in a branch so it can be played with. (In particular, it needs Keybinder 3.0 added as a dependency to the deb, which I don't really know how to do, but I'm sure Martin does.) This doesn't deal with the "how do we get launched and closed by keypress" issue, because that's about the desktop itself doing that and Magnus just responding to it, but it's a start.

**Comment by fossfreedom** [comment]
Thanks for the feedback - much appreciated.

> Does Budgie already have a "launch desktop magnifier" option in its global keyboard shortcuts control panel? If it does... what does using that keypress actually do?

Budgie Desktop in this case has access to the GNOME Shell Keyboard Settings "Accessibility Zoom" options which I presume launches the GNOME Shell magnifier ... which we cannot use since its GNOME Shell only.  From a quick look -  the zoom options are dconf (gsettings) keys to switch on/off, zoom in and zoom out.  So I will need to write a tiny bit of code to sit on those keys and call your app with whatever method @flexiondotorg and your good-self agree on.

Re  "--toggle" option: obviously I would need somehow to work out if the magnifier window is already open/closed. Will also need to work out how to reset the dconf keys if the magnifier is manually closed/manualy opened.  Kind of messy I'm guessing.

I presume if at all possible - "--zoom-in" and "--zoom-out" options is a possibility to be added?

I'm not really familiar how GNOME Shell handles its magnifier (https://github.com/GNOME/gnome-shell/blob/master/js/ui/magnifier.js & https://github.com/GNOME/gnome-shell/blob/d80e7e011874f323639929e1650781beb7ff9bc4/js/ui/magnifierDBus.js) - i.e. if it uses freedesktop standards or not.

**Comment by stuartlangridge** [comment]
@fossfreedom well. We believe (thanks to help from @ted-gould in https://social.gould.cx/@ted/102224935064799224) that the autostart .desktop file that @flexiondotorg added in https://github.com/stuartlangridge/magnus/commit/df5a269d2a36793b301889aaddc9701090311f2c should just make everything work; doing Budgie's keypress to launch a magnifier actually sets and unsets the GSettings key `org.gnome.desktop.a11y.applications/screen-magnifier-enabled`, and we think that that should already work. And the `.desktop` file mentions that key as its startup property, and so `gnome-session` should notice that and start up Magnus when that key changes... which means that I think that this all should _already_ work on Budgie. I am interested to hear whether this is the case! (There hasn't been a deb released with this code in it yet, though.)

So, starting up magnus with the keypress should already work. We're also interested to hear whether using the keypress again to set the GSettings key to false will _stop_ the app, or whether the app has to monitor the GSettings key itself and shut itself down when the key goes false. But I'm on MATE, which has mate-settings-daemon rather than gnome-settings-daemon and gnome-session, and that currently has a bug which stops all this working. So... if you can test this and see whether it works, or if it doesn't where the logic falls down, that would be great.

**Comment by fossfreedom** [comment]
Ah - cool - learn something everyday :)

For Budgie I had to adjust the autostart file to:

```
[Desktop Entry]
Type=Application
Name=Magnus screen magnifier
Exec=magnus
NoDisplay=true
#AutostartCondition=AutostartCondition=GSettings org.gnome.desktop.a11y.applications screen-magnifier-enabled
AutostartCondition=GSettings org.gnome.desktop.a11y.applications screen-magnifier-enabled
X-GNOME-AutoRestart=true
OnlyShowIn=Budgie
#NotShowIn=GNOME;
```

Can confirm Alt+Super+8 starts and stops magnus correctly.  Edge case of manually closing the magnifier means you have to Alt+Super+8 twice to fire it up again - not really an issue.
i.e.X-GNOME-AutoRestart, different AutoStartCondition and using OnlyShowIn=Budgie

i.e. Budgie-Desktop uses Budgie:GNOME for its XDG_CURRENT_DESKTOP

**Comment by stuartlangridge** [comment]
Interesting. So... we should detect if we're started by keypress, and if we are and we're manually closed, set the flag back to false. The best way I can think of to do that is to have the autostart desktop file `Exec` line (but not the normal desktop file) be `magnus --started-by-keypress` or similar (and then poke the code to care about that command line option), but I'm open to thoughts on better ways to do that if there are any.

**Comment by fossfreedom** [comment]
`magnus --started-by-keypress` seems reasonable to me.

On a slightly different tack - the keybinding Alt+Super+plus doesnt work on my keyboard - the + is above the equals sign.  I changed to Alt+Super+equal and then the zoom works correctly.

**Comment by stuartlangridge** [comment]
OK, I've made a couple of small changes to master which implement that change. @fossfreedom you'll still need to change the `OnlyShowIn` stuff, but I think everything else should work as described above now. (I've also fixed the zoom in `+` keybinding so that it binds to `+` and `=`.)

As regards the `OnlyShowIn`, I don't really understand what it's for; @flexiondotorg do you have it set to NotShowIn=GNOME for a reason? Since Budgie obviously want the opposite of that...

**Comment by flexiondotorg** [comment]
NotShowIn=GNOME was an attempt to prevent Magnus being invoked on GNOME Shell where they have a screen magnifier baked into their shell.

We should do, be default, what works for Budgie IMO. So a PR to correct it would be good 👍

**Comment by stuartlangridge** [comment]
Agreed. My inclination is also that explicitly installing Magnus indicates that you want to override the default system magnifier, otherwise there'd be no way to override it. So I think we don't need the gnome line, if Budgie are happy with that and want to do a PR to what the desktop file should be

**Comment by fossfreedom** [comment]
this has all now been resolved.  Thanks
